# Build GitHub release artifacts: latest.yml, SHA256SUMS, release-notes.md
import os
import hashlib
import datetime

WORK = r"C:\ChoyeonExercises\1.0.12"
APK_NAME = "ChoyeonExercises-v1.0.12.apk"
APK_PATH = os.path.join(WORK, APK_NAME)

SIZE = os.path.getsize(APK_PATH)
h = hashlib.sha256()
with open(APK_PATH, "rb") as f:
    for chunk in iter(lambda: f.read(1 << 20), b""):
        h.update(chunk)
SHA = h.hexdigest()
SHA_UP = SHA.upper()
SIZE_MB = round(SIZE / 1024 / 1024, 2)

# 1. SHA256SUMS
with open(os.path.join(WORK, "SHA256SUMS"), "w", encoding="ascii", newline="\n") as f:
    f.write(f"{SHA} *{APK_NAME}\n")

# 2. latest.yml (Electron updater format)
today_iso = datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S.000Z")
just_date = datetime.date.today().isoformat()
yml = (
    f"version: 1.0.12\n"
    f"files:\n"
    f"  - url: {APK_NAME}\n"
    f"    sha512: {SHA}\n"
    f"    size: {SIZE}\n"
    f"    releaseDate: {just_date}\n"
    f"path: {APK_NAME}\n"
    f"sha256: {SHA}\n"
    f"releaseDate: {today_iso}\n"
)
with open(os.path.join(WORK, "latest.yml"), "w", encoding="utf-8", newline="\n") as f:
    f.write(yml)

# 3. release-notes.md (literal braces {{count}} / {{month}}, {{day}} avoid f-string eval)
notes = f"""# ChoyeonExercises v1.0.12

## Critical Android Install Fix: 解析程序包时出现问题 (Install-Error 120203)
Removed 6 unprotected META-INF entries generated by AGP 8.6.1 that caused strict OEM
installers (Tencent Security, Android 16 package parsers on OPPO/vivo/OnePlus/etc.)
to reject the APK with a JarFile vs JarInputStream signature mismatch.

- Stripped: app-metadata.properties, version-control-info.textproto,
  kotlin.reflect.jvm.impl.builtins.BuiltInsLoader,
  kotlin.reflect.jvm.impl.resolve.ExternalOverridabilityCondition,
  kotlinx.coroutines.CoroutineExceptionHandler,
  kotlinx.coroutines.internal.MainDispatcherFactory
- Re-signed via apksigner with **V1 (JAR) + V2 (APK Signature Scheme)** both
  explicitly enabled (V3/V4 disabled for broad installer compatibility).
- Final META-INF contains ONLY: MANIFEST.MF, CHOYEON.SF, CHOYEON.RSA (3 files, all
  signature protected).
- apksigner verify: **0 WARNINGS, 0 ERRORS — V1=true, V2=true**

## i18n Fixes: 3 missing keys + hardcoded strings eliminated
- `workoutSession.doneTitle` / `workoutSession.emptyFinishTitle` (end-session dialog)
- `workout.deleteOneTitle` (single history-item delete confirm)
- Sunday..Saturday weekday calendar → `t('compact.daySun')` … `t('compact.daySat')`
- Training card meta line (3 workouts · 48 sets) → `t('workout.activeCardMeta', {{ count }})`
- Date format (06/01) → `t('workout.dateMonthDay', {{ month }}, {{ day }})`
- Library subtitle `EXERCISE` → `t('compact.exercises')`

## Settings-Sync Persistence Key Fix (Language/Theme Lost on Restart)
`settings-sync.ts:loadSettings()` now **reads `@choyeon/vault/v2` first** (the actual
zustand persist 1.2 storage key used by useAppStore v2) instead of the legacy
`@choyeon/settings` key. Language toggle, rest timer, haptic and theme settings now
correctly survive a cold app reboot.

## UI/UX Logic Optimizations
- `ExerciseCard`: `memo(ExerciseCardImpl)` + `useCallback` press handlers. No stale
  re-renders in the 1324-item home grid or library list.
- `Workout.tsx` / `Profile.tsx`: streak, totals, volume computed via `useMemo` instead
  of re-deriving on every props/state tick.
- `workout/start.tsx`: added `navPoppedRef` guard. Prevents double-navigation-back
  bug when the `activeWorkout` subscription fires during `replace()`.
- Router calls: removed `as any` casts → typed `Parameters<typeof router.push>[0]`.
- Store: `DEFAULT_SESSION_NAME_FALLBACK` typed `{{ [k in 'zh'|'en']: string }}`;
  `startWorkout()` picks the default session name through `i18nInstance.t(...)`
  instead of the hardcoded Chinese fallback.

## Build Stability
- Codegen stub auto-recovery after `expo prebuild --clean`: CMake `codegen/jni` stubs
  are recreated for expo-modules-core, reanimated, worklets, async-storage, screens,
  constants, safe-area-context, image, masked-view + 13 other expo autolinked pkgs.
- Pinned: AGP 8.6.1 · compileSdk=35 · targetSdkVersion=33 · NDK
  abiFilters=arm64-v8a,armeabi-v7a (APK shrank 113 MB → {SIZE_MB} MB).
- Gradle flags: `newArchEnabled=false`, `hermesEnabled=true`,
  `EX_DEV_CLIENT_NETWORK_INSPECTOR=false`, `expo.useLegacyPackaging=true`,
  `android.signingConfig.v1SigningEnabled=true`,
  `android.enableAppMetadataInApk=false`,
  `android.enableVersionControlInfoInApk=false`.

## Version Info
- App:         1.0.12 (versionCode 13)
- Expo SDK:    57 (React Native 0.82)
- Android:     minSdk 24 · targetSdk 33
- Size:        {SIZE_MB} MB
- SHA256:      {SHA_UP}
"""
with open(os.path.join(WORK, "release-notes.md"), "w", encoding="utf-8", newline="\n") as f:
    f.write(notes)

# Summary
print(f"SHA256 = {SHA_UP}")
print(f"SIZE   = {SIZE} bytes ({SIZE_MB} MB)")
print("Artifacts ready:")
for n in (APK_NAME, "latest.yml", "SHA256SUMS", "release-notes.md"):
    p = os.path.join(WORK, n)
    print(f"  {n}  —  {round(os.path.getsize(p)/1024,1)} KB")
