"""
Fitness name Chinese translator (v2, clean rewrite).
Phase A: compounds longest-first on word boundaries
Phase B: word-by-word, with multi-lookup for hyphen/combined tokens
Phase C: human-curated override table for the weird 120 names
"""
from __future__ import annotations
import json, re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src" / "data" / "exercises.json"

# =========================================================================
# 1) COMPOUND PHRASES  —  longest-first, word-bounded regex sub
# =========================================================================
COMPOUNDS: list[tuple[str, str]] = [
    # ---- 三大项 + 基础复合动作
    ("romanian deadlift", "罗马尼亚硬拉"),
    ("stiff leg deadlift", "直腿硬拉"),
    ("stiff-legged deadlift", "直腿硬拉"),
    ("sumo deadlift", "相扑硬拉"),
    ("trap bar deadlift", "六角杠硬拉"),
    ("hex bar deadlift", "六角杠硬拉"),
    ("conventional deadlift", "传统硬拉"),
    ("snatch grip deadlift", "宽握硬拉"),
    ("deficit deadlift", "赤字硬拉"),
    ("single-leg deadlift", "单腿硬拉"),
    ("single leg deadlift", "单腿硬拉"),
    ("front squat", "前蹲"),
    ("back squat", "后蹲"),
    ("goblet squat", "高脚杯深蹲"),
    ("bulgarian split squat", "保加利亚分腿蹲"),
    ("split squat", "分腿蹲"),
    ("hack squat", "哈克深蹲"),
    ("box squat", "箱式深蹲"),
    ("zercher squat", "泽奇深蹲"),
    ("overhead squat", "过头深蹲"),
    ("sissy squat", "茜茜深蹲"),
    ("paused squat", "停顿深蹲"),
    ("tempo squat", "节奏深蹲"),
    ("pistol squat", "单腿深蹲"),
    ("squat jump", "深蹲跳"),
    ("jump squat", "深蹲跳"),
    ("barbell squat", "杠铃深蹲"),
    ("dumbbell squat", "哑铃深蹲"),
    ("kettlebell squat", "壶铃深蹲"),
    ("bench press", "卧推"),
    ("incline bench press", "上斜卧推"),
    ("decline bench press", "下斜卧推"),
    ("close-grip bench press", "窄距卧推"),
    ("close grip bench press", "窄距卧推"),
    ("wide-grip bench press", "宽距卧推"),
    ("wide grip bench press", "宽距卧推"),
    ("reverse-grip bench press", "反握卧推"),
    ("reverse grip bench press", "反握卧推"),
    ("barbell bench press", "杠铃卧推"),
    ("dumbbell bench press", "哑铃卧推"),
    ("spoto press", "斯波托卧推"),
    ("board press", "板卧推"),
    ("floor press", "地板卧推"),
    ("pin press", "架上推举"),
    ("jm press", "JM 推举"),
    ("skull crusher", "碎颅臂屈伸"),
    ("skullcrusher", "碎颅臂屈伸"),
    ("skull press", "碎颅臂屈伸"),
    ("clean and press", "挺举推举"),
    ("clean and jerk", "挺举"),
    ("power clean", "力量翻"),
    ("hang clean", "悬垂翻"),
    ("clean-grip front squat", "翻握前蹲"),
    ("clean grip front squat", "翻握前蹲"),
    ("squat clean", "深蹲翻"),
    ("power snatch", "力量抓"),
    ("hang snatch", "悬垂抓"),
    ("dumbbell snatch", "哑铃抓举"),
    ("one arm dumbbell snatch", "单臂哑铃抓举"),
    ("single arm dumbbell snatch", "单臂哑铃抓举"),
    ("good morning", "早安式"),
    ("good-morning", "早安式"),
    ("hip thrust", "臀推"),
    ("hip thrusts", "臀推"),
    ("glute bridge", "臀桥"),
    ("glute-ham raise", "腿背屈伸"),
    ("glute ham raise", "腿背屈伸"),
    ("nordic curl", "北欧腿弯举"),
    ("nordic hamstring curl", "北欧腿弯举"),
    ("reverse hyper", "反向挺身"),
    ("back extension", "山羊挺身"),
    ("hyperextension", "挺身"),
    # ---- 胸
    ("cable crossover", "绳索夹胸"),
    ("pec deck fly", "蝴蝶机飞鸟"),
    ("pec dec fly", "蝴蝶机飞鸟"),
    ("cable fly", "绳索飞鸟"),
    ("machine fly", "器械飞鸟"),
    ("chest fly", "胸部飞鸟"),
    ("chest flyes", "胸部飞鸟"),
    ("chest flies", "胸部飞鸟"),
    ("dumbbell fly", "哑铃飞鸟"),
    ("incline dumbbell fly", "上斜哑铃飞鸟"),
    ("decline dumbbell fly", "下斜哑铃飞鸟"),
    ("incline fly", "上斜飞鸟"),
    ("decline fly", "下斜飞鸟"),
    ("flat fly", "平板飞鸟"),
    ("cable flyes", "绳索飞鸟"),
    ("guillotine bench press", "断头台卧推"),
    ("spider curl", "蜘蛛弯举"),
    ("preacher curl", "斜托弯举"),
    ("hammer curl", "锤式弯举"),
    ("concentration curl", "集中弯举"),
    ("bayesian curl", "贝叶斯弯举"),
    ("cheat curl", "借力弯举"),
    ("drag curl", "拖拽弯举"),
    ("bicep curl", "二头弯举"),
    ("biceps curl", "二头弯举"),
    ("alternate bicep curl", "交替二头弯举"),
    ("alternate biceps curl", "交替二头弯举"),
    ("alternating bicep curl", "交替二头弯举"),
    ("alternating biceps curl", "交替二头弯举"),
    ("cross body curl", "交叉弯举"),
    ("cross-body curl", "交叉弯举"),
    ("wrist curl", "腕弯举"),
    ("reverse curl", "反握弯举"),
    ("standing curl", "站姿弯举"),
    ("seated curl", "坐姿弯举"),
    ("lying curl", "仰卧弯举"),
    ("incline curl", "上斜弯举"),
    ("cable curl", "绳索弯举"),
    ("barbell curl", "杠铃弯举"),
    ("dumbbell curl", "哑铃弯举"),
    # ---- 三头
    ("triceps pushdown", "三头下压"),
    ("tricep pushdown", "三头下压"),
    ("triceps pressdown", "三头下压"),
    ("tricep pressdown", "三头下压"),
    ("triceps extension", "三头伸展"),
    ("tricep extension", "三头伸展"),
    ("overhead triceps extension", "过头三头伸展"),
    ("overhead tricep extension", "过头三头伸展"),
    ("triceps kickback", "三头后踢"),
    ("tricep kickback", "三头后踢"),
    # ---- 背
    ("bent over row", "俯身划船"),
    ("bent-over row", "俯身划船"),
    ("seated row", "坐姿划船"),
    ("pendlay row", "彭德莱划船"),
    ("yates row", "耶茨划船"),
    ("t-bar row", "T 杠划船"),
    ("t bar row", "T 杠划船"),
    ("chest supported row", "俯卧划船"),
    ("chest-supported row", "俯卧划船"),
    ("meadows row", "梅多斯划船"),
    ("landmine row", "地雷管划船"),
    ("single arm row", "单臂划船"),
    ("single-arm row", "单臂划船"),
    ("renegade row", "反叛者划船"),
    ("upright row", "直立划船"),
    ("inverted row", "反向划船"),
    ("kroc row", "克罗克划船"),
    ("gorilla row", "大猩猩划船"),
    ("dumbbell row", "哑铃划船"),
    ("barbell row", "杠铃划船"),
    ("cable row", "绳索划船"),
    ("lat pulldown", "高位下拉"),
    ("lat pull down", "高位下拉"),
    ("lat pull-down", "高位下拉"),
    ("wide-grip lat pulldown", "宽距高位下拉"),
    ("close-grip lat pulldown", "窄距高位下拉"),
    ("underhand lat pulldown", "反握高位下拉"),
    ("reverse-grip lat pulldown", "反握高位下拉"),
    ("pull up", "引体向上"),
    ("pull-up", "引体向上"),
    ("chin up", "反握引体向上"),
    ("chin-up", "反握引体向上"),
    ("muscle up", "双力臂"),
    ("muscle-up", "双力臂"),
    ("archer pull up", "射手引体"),
    ("archer pull-up", "射手引体"),
    ("typewriter pull up", "打字机引体"),
    ("archer row", "射手划船"),
    ("bent arm pullover", "屈臂上拉"),
    ("straight arm pullover", "直臂上拉"),
    ("straight-arm pullover", "直臂上拉"),
    ("straight arm pulldown", "直臂下压"),
    ("straight-arm pulldown", "直臂下压"),
    ("pull through", "拉过腿"),
    ("pull-through", "拉过腿"),
    ("face pull", "面拉"),
    ("high pull", "高拉"),
    # ---- 腿
    ("leg press", "腿举"),
    ("leg extension", "腿伸展"),
    ("leg curl", "腿弯举"),
    ("seated leg curl", "坐姿腿弯举"),
    ("lying leg curl", "俯卧腿弯举"),
    ("standing leg curl", "站姿腿弯举"),
    ("calf raise", "提踵"),
    ("standing calf raise", "站姿提踵"),
    ("seated calf raise", "坐姿提踵"),
    ("donkey calf raise", "驴式提踵"),
    ("calf press", "腿举提踵"),
    ("walking lunge", "行走弓步"),
    ("walking lunges", "行走弓步"),
    ("reverse lunge", "后撤弓步"),
    ("reverse lunges", "后撤弓步"),
    ("back lunge", "后撤弓步"),
    ("forward lunge", "前迈弓步"),
    ("front lunge", "前迈弓步"),
    ("side lunge", "侧弓步"),
    ("lateral lunge", "侧弓步"),
    ("split lunge", "分腿弓步"),
    ("curtsy lunge", "屈膝礼弓步"),
    ("bulgarian lunge", "保加利亚弓步"),
    ("step up", "台阶上步"),
    ("step-up", "台阶上步"),
    ("box jump", "跳箱"),
    ("box jumps", "跳箱"),
    ("bulgarian split squat", "保加利亚分腿蹲"),
    ("single-leg squat", "单腿深蹲"),
    ("single leg squat", "单腿深蹲"),
    # ---- 肩
    ("overhead press", "过头推举"),
    ("standing overhead press", "站姿过头推举"),
    ("seated overhead press", "坐姿过头推举"),
    ("military press", "军式推举"),
    ("push press", "借力推举"),
    ("arnold press", "阿诺德推举"),
    ("bradford press", "布拉德福德推举"),
    ("bradford rocky press", "布拉德福洛基推举"),
    ("cuban press", "古巴推举"),
    ("shoulder press", "肩推"),
    ("seated shoulder press", "坐姿肩推"),
    ("standing shoulder press", "站姿肩推"),
    ("dumbbell shoulder press", "哑铃肩推"),
    ("dumbbell press", "哑铃推举"),
    ("barbell press", "杠铃推举"),
    ("lateral raise", "侧平举"),
    ("lateral raises", "侧平举"),
    ("side lateral raise", "侧平举"),
    ("bent over lateral raise", "俯身侧平举"),
    ("front raise", "前平举"),
    ("front raises", "前平举"),
    ("forward raise", "前平举"),
    ("rear delt fly", "后束飞鸟"),
    ("rear delt flyes", "后束飞鸟"),
    ("rear delt raise", "后束平举"),
    ("rear delt row", "后束划船"),
    ("face pull", "面拉"),
    ("upright row", "直立划船"),
    ("halo", "绕肩"),
    # ---- 核心
    ("crunch", "卷腹"),
    ("crunches", "卷腹"),
    ("sit up", "仰卧起坐"),
    ("sit-up", "仰卧起坐"),
    ("leg raise", "举腿"),
    ("leg raises", "举腿"),
    ("hanging leg raise", "悬垂举腿"),
    ("hanging knee raise", "悬垂屈膝举腿"),
    ("knee raise", "屈膝举腿"),
    ("v-up", "V 字起身"),
    ("v up", "V 字起身"),
    ("toe touch", "触脚尖"),
    ("toe touches", "触脚尖"),
    ("russian twist", "俄罗斯转体"),
    ("plank", "平板支撑"),
    ("side plank", "侧平板支撑"),
    ("bird dog", "鸟狗式"),
    ("dead bug", "死虫式"),
    ("hollow body hold", "空心保持"),
    ("superman", "超人式"),
    ("flutter kick", "踢腿"),
    ("scissor kick", "剪刀腿"),
    ("bicycle crunch", "自行车卷腹"),
    ("reverse crunch", "反向卷腹"),
    ("wood chop", "伐木"),
    ("wood chopper", "伐木"),
    ("pallof press", "帕洛夫推"),
    ("cable crunch", "绳索卷腹"),
    ("landmine twist", "地雷管扭转"),
    ("cable twist", "绳索转体"),
    ("torso rotation", "躯干旋转"),
    ("trunk rotation", "躯干旋转"),
    ("side bend", "侧弯"),
    ("side bends", "侧弯"),
    ("cable side bend", "绳索侧弯"),
    ("oblique crunch", "腹斜卷腹"),
    ("twisting crunch", "扭转卷腹"),
    ("cable oblique twist", "绳索腹斜转体"),
    ("twisting", "扭转"),
    ("jack knife sit-up", "折刀仰卧起坐"),
    ("jackknife sit-up", "折刀仰卧起坐"),
    ("kneeling twisting crunch", "跪姿扭转卷腹"),
    ("standing twisting crunch", "站姿扭转卷腹"),
    # ---- 推 / 拉 / 双杠
    ("push up", "俯卧撑"),
    ("push-up", "俯卧撑"),
    ("incline push up", "上斜俯卧撑"),
    ("decline push up", "下斜俯卧撑"),
    ("diamond push up", "钻石俯卧撑"),
    ("wide push up", "宽距俯卧撑"),
    ("spider push up", "蜘蛛俯卧撑"),
    ("pike push up", "折刀俯卧撑"),
    ("clap push up", "击掌俯卧撑"),
    ("planche push up", "俄挺俯卧撑"),
    ("ring push up", "吊环俯卧撑"),
    ("knee push up", "膝式俯卧撑"),
    ("handstand push up", "倒立撑"),
    ("archer push up", "射手俯卧撑"),
    ("dips", "双杠臂屈伸"),
    ("dip", "双杠臂屈伸"),
    ("triceps dip", "双杠臂屈伸"),
    ("bench dip", "凳上臂屈伸"),
    ("chair dips", "椅上臂屈伸"),
    # ---- 有氧 & 代谢调节
    ("battle rope", "战绳"),
    ("battle ropes", "战绳"),
    ("battling ropes", "战绳"),
    ("jump rope", "跳绳"),
    ("jumping jack", "开合跳"),
    ("jumping jacks", "开合跳"),
    ("mountain climber", "登山跑"),
    ("mountain climbers", "登山跑"),
    ("burpee", "波比跳"),
    ("burpees", "波比跳"),
    ("thruster", "蹲推"),
    ("thrusters", "蹲推"),
    ("wall ball", "墙球"),
    ("bear crawl", "熊爬"),
    ("crab walk", "螃蟹走"),
    ("duck walk", "鸭步走"),
    ("inchworm", "尺蠖走"),
    ("high knees", "高抬腿"),
    ("butt kick", "后踢腿"),
    ("butt kicks", "后踢腿"),
    ("jog in place", "原地跑"),
    ("skipping", "跳绳"),
    # ---- 搬运 & 负荷
    ("farmer carry", "农夫行走"),
    ("farmer's carry", "农夫行走"),
    ("farmers walk", "农夫行走"),
    ("farmer carry", "农夫行走"),
    ("suitcase carry", "手提箱行走"),
    ("goblet carry", "高脚杯行走"),
    ("rack carry", "架上行走"),
    ("overhead carry", "过头行走"),
    ("zombie walk", "僵尸行走"),
    ("waiter carry", "侍者行走"),
    ("cross body carry", "交叉体行走"),
    # ---- 耸肩 / 腕 / 前臂 / 颈
    ("shrug", "耸肩"),
    ("shrugs", "耸肩"),
    ("barbell shrug", "杠铃耸肩"),
    ("dumbbell shrug", "哑铃耸肩"),
    ("cable shrug", "绳索耸肩"),
    ("trap bar shrug", "六角杠耸肩"),
    ("neck curl", "颈弯举"),
    ("neck extension", "颈伸展"),
    ("wrist roller", "卷腕"),
    ("plate pinch", "片夹"),
    ("band pull apart", "弹力带外展"),
    ("band pull-apart", "弹力带外展"),
    ("pull apart", "拉力外展"),
    ("pull-apart", "拉力外展"),
    ("grip crush", "握力训练"),
    ("plate curl", "铃片弯举"),
    # ---- 壶铃
    ("kettlebell swing", "壶铃摇摆"),
    ("kettlebell clean", "壶铃翻"),
    ("kettlebell snatch", "壶铃抓举"),
    ("kettlebell goblet squat", "壶铃高脚杯深蹲"),
    ("turkish get up", "土耳其起身"),
    ("turkish get-up", "土耳其起身"),
    # ---- 器械 + 握法 + 位姿 (优先)
    ("smith machine", "史密斯机"),
    ("cable machine", "绳索机"),
    ("hack squat machine", "哈克深蹲机"),
    ("lever machine", "杠杆机"),
    ("leverage machine", "杠杆机"),
    ("chest press machine", "推胸机"),
    ("fly machine", "飞鸟机"),
    ("pec deck", "蝴蝶机"),
    ("pec dec", "蝴蝶机"),
    ("leg press machine", "腿举机"),
    ("rowing machine", "划船机"),
    ("assisted machine", "辅助机"),
    ("power rack", "力量架"),
    ("squat rack", "深蹲架"),
    ("ez barbell", "EZ 曲杆"),
    ("ez bar", "EZ 曲杆"),
    ("olympic barbell", "奥杆"),
    ("trap bar", "六角杠"),
    ("hex bar", "六角杠"),
    ("t-bar", "T 杠"),
    ("t bar", "T 杠"),
    ("landmine", "地雷管"),
    ("medicine ball", "药球"),
    ("stability ball", "稳定球"),
    ("exercise ball", "瑜伽球"),
    ("swiss ball", "瑞士球"),
    ("physio ball", "瑜伽球"),
    ("resistance band", "弹力带"),
    ("mini band", "迷你带"),
    ("foam roller", "泡沫轴"),
    ("ab wheel", "健腹轮"),
    ("ab roller", "健腹轮"),
    ("step mill", "登山机"),
    ("stairmaster", "登山机"),
    ("stationary bike", "动感单车"),
    ("assisted pull-up", "辅助引体"),
    ("assisted dip", "辅助臂屈伸"),
    ("parallettes", "双杠架"),
    ("plyo box", "跳箱"),
    ("arm blaster", "臂爆炸器"),
    # ---- Body-part 复合 (posture + modifier + body)
    ("rectus femoris", "股直肌"),
    ("piriformis", "梨状肌"),
    ("pectoralis major", "胸大肌"),
    ("pectoralis minor", "胸小肌"),
    ("gluteus maximus", "臀大肌"),
    ("gluteus medius", "臀中肌"),
    ("gluteus minimus", "臀小肌"),
    ("biceps femoris", "股二头肌"),
    ("vastus medialis", "股内侧肌"),
    ("vastus lateralis", "股外侧肌"),
    ("vastus intermedius", "股中间肌"),
    ("erector spinae", "竖脊肌"),
    ("gastrocnemius", "腓肠肌"),
    ("soleus", "比目鱼肌"),
    ("tibialis anterior", "胫骨前肌"),
    ("transversus abdominis", "腹横肌"),
    ("rectus abdominis", "腹直肌"),
    ("multifidus", "多裂肌"),
    ("latissimus dorsi", "背阔肌"),
    ("teres major", "大圆肌"),
    ("teres minor", "小圆肌"),
    ("rhomboid major", "大菱形肌"),
    ("rhomboid minor", "小菱形肌"),
    ("trapezius", "斜方肌"),
    ("deltoid", "三角肌"),
    ("anterior deltoid", "三角肌前束"),
    ("lateral deltoid", "三角肌中束"),
    ("posterior deltoid", "三角肌后束"),
    ("rotator cuff", "肩袖"),
    ("supraspinatus", "冈上肌"),
    ("serratus anterior", "前锯肌"),
    ("levator scapulae", "肩胛提肌"),
    ("sternocleidomastoid", "胸锁乳突肌"),
    ("brachialis", "肱肌"),
    ("brachioradialis", "肱桡肌"),
    # ---- 握法 / 姿态
    ("narrow grip", "窄距"),
    ("close grip", "窄距"),
    ("close-grip", "窄距"),
    ("wide grip", "宽距"),
    ("wide-grip", "宽距"),
    ("neutral grip", "中立握"),
    ("underhand grip", "反握"),
    ("overhand grip", "正握"),
    ("pronated grip", "正握"),
    ("supinated grip", "反握"),
    ("reverse grip", "反握"),
    ("reverse-grip", "反握"),
    ("mixed grip", "混合握"),
    ("hook grip", "锁握"),
    ("false grip", "假握"),
    ("narrow stance", "窄站距"),
    ("wide stance", "宽站距"),
    ("sumo stance", "相扑站距"),
    ("single arm", "单臂"),
    ("single-arm", "单臂"),
    ("single leg", "单腿"),
    ("single-leg", "单腿"),
    ("one arm", "单臂"),
    ("one-arm", "单臂"),
    ("one leg", "单腿"),
    ("one-leg", "单腿"),
    ("two arm", "双臂"),
    ("two arms", "双臂"),
    ("two leg", "双腿"),
    ("two legs", "双腿"),
    ("both arms", "双臂"),
    ("both legs", "双腿"),
    ("alternate arm", "交替手臂"),
    ("alternating arm", "交替手臂"),
    ("alternate leg", "交替腿"),
    ("alternating leg", "交替腿"),
    ("half kneeling", "半跪"),
    ("half-kneeling", "半跪"),
    ("kneeling", "跪姿"),
    ("seated", "坐姿"),
    ("standing", "站姿"),
    ("lying", "仰卧"),
    ("prone", "俯卧"),
    ("supine", "仰卧"),
    ("bent over", "俯身"),
    ("bent-over", "俯身"),
    ("flat bench", "平板凳"),
    ("incline bench", "上斜凳"),
    ("decline bench", "下斜凳"),
    ("behind the neck", "颈后"),
    ("behind neck", "颈后"),
    ("behind the head", "头后"),
    ("behind head", "头后"),
    ("in front of head", "头前"),
    ("in front of the body", "体前"),
    ("knees bent", "屈膝"),
    ("bent knees", "屈膝"),
    ("legs straight", "直腿"),
    ("straight legs", "直腿"),
    ("palms down", "掌心向下"),
    ("palms up", "掌心向上"),
    ("palms forward", "掌心向前"),
    ("palms facing forward", "掌心向前"),
    ("palms facing each other", "掌心相对"),
    ("palms inward", "掌心向内"),
    ("palms outward", "掌心向外"),
    ("palms facing in", "掌心向内"),
    ("palms facing out", "掌心向外"),
    ("bodyweight", "自重"),
    ("weighted", "负重"),
    ("assisted", "辅助"),
    ("unassisted", "无辅助"),
    ("paused", "停顿"),
    ("tempo", "节奏"),
    ("isometric", "静力"),
    ("isolation", "孤立"),
    ("compound", "复合"),
    ("partial", "半程"),
    ("full range of motion", "全幅度"),
    ("full rom", "全幅度"),
    # ---- stretch 相关
    ("cobra stretch", "眼镜蛇拉伸"),
    ("cat-cow stretch", "猫牛拉伸"),
    ("child's pose", "婴儿式"),
    ("child pose", "婴儿式"),
    ("pigeon pose", "鸽子式"),
    ("downward dog", "下犬式"),
    ("upward dog", "上犬式"),
    ("frog stretch", "青蛙拉伸"),
    ("pancake stretch", "煎饼拉伸"),
    ("straddle stretch", "分腿拉伸"),
    ("butterfly stretch", "蝴蝶拉伸"),
    ("seated forward fold", "坐姿前屈"),
    ("standing forward fold", "站姿前屈"),
    ("hip flexor stretch", "髋屈肌拉伸"),
    ("hamstring stretch", "腘绳拉伸"),
    ("quad stretch", "股四拉伸"),
    ("calf stretch", "小腿拉伸"),
    ("chest stretch", "胸部拉伸"),
    ("chest opener", "开胸"),
    ("shoulder stretch", "肩部拉伸"),
    ("triceps stretch", "三头拉伸"),
    ("biceps stretch", "二头拉伸"),
    ("neck stretch", "颈部拉伸"),
    ("upper back stretch", "上背拉伸"),
    ("lower back stretch", "下背拉伸"),
    ("wrist stretch", "腕部拉伸"),
    ("ankle stretch", "踝关节拉伸"),
    ("piriformis stretch", "梨状肌拉伸"),
    ("glute stretch", "臀部拉伸"),
    # ---- 街健 / 静态力量
    ("iron cross", "十字支撑"),
    ("human flag", "人旗"),
    ("front lever", "前水平"),
    ("back lever", "后水平"),
    ("planche", "俄挺"),
    ("tuck planche", "团身俄挺"),
    ("straddle planche", "分腿俄挺"),
    ("full planche", "全俄挺"),
    ("l-sit", "L 坐"),
    ("l sit", "L 坐"),
    ("v-sit", "V 坐"),
    ("hollow body", "空心体"),
    ("arch body", "弓形"),
    ("skin the cat", "猫翻身"),
    ("back bridge", "后桥"),
    ("neck bridge", "颈桥"),
    ("handstand", "倒立"),
    ("headstand", "头倒立"),
    ("frog stand", "青蛙撑"),
    ("crow pose", "乌鸦式"),
    # ---- 通用描述
    ("ankle circles", "踝关节环绕"),
    ("wrist circles", "腕关节环绕"),
    ("hip circles", "髋关节环绕"),
    ("arm circles", "手臂环绕"),
    ("neck circles", "颈部环绕"),
    ("balance board", "平衡板"),
    ("battling ropes", "战绳"),
    ("tire flip", "翻轮胎"),
    ("sled push", "推雪橇"),
    ("sled pull", "拉雪橇"),
    ("sledgehammer swing", "大锤挥击"),
    ("sandbag clean", "沙袋翻"),
    ("sandbag throw", "沙袋投"),
    ("weighted carry", "负重行走"),
    ("loaded carry", "负重行走"),
    ("bottoms up", "举杯式"),
    ("heel touchers", "交替触脚跟"),
    ("heel touches", "交替触脚跟"),
    ("heel taps", "交替触脚跟"),
    ("all fours", "四点支撑"),
    ("hands and knees", "四点支撑"),
    ("bear position", "熊姿"),
    ("crab position", "蟹姿"),
    ("supine position", "仰卧姿"),
    ("prone position", "俯卧姿"),
]

# =========================================================================
# 2) WORD-LEVEL dictionary  (single token, applied after compounds)
# =========================================================================
WORDS: dict[str, str] = {
    # 器械
    "barbell": "杠铃",
    "dumbbell": "哑铃",
    "dumbbells": "哑铃",
    "kettlebell": "壶铃",
    "kettlebells": "壶铃",
    "cable": "绳索",
    "band": "弹力带",
    "bands": "弹力带",
    "machine": "器械",
    "smith": "史密斯机",
    "landmine": "地雷管",
    "dumbell": "哑铃",
    "bar": "杠",
    "bell": "铃",
    "ez": "EZ",
    "olympic": "奥林匹克",
    "trap": "六角",
    "hex": "六角",
    "plate": "铃片",
    "plates": "铃片",
    "bench": "凳",
    "box": "箱",
    "wall": "墙",
    "mat": "垫",
    "ball": "球",
    "roller": "轴",
    "foam": "泡沫",
    "rope": "绳",
    "ropes": "绳",
    "trx": "TRX",
    "rings": "吊环",
    "ring": "吊环",
    "suspension": "悬挂",
    "bike": "单车",
    "treadmill": "跑步机",
    "elliptical": "椭圆机",
    "rower": "划船机",
    "sledgehammer": "大锤",
    "hammer": "大锤",
    "tire": "轮胎",
    "sled": "雪橇",
    "sandbag": "沙袋",
    "plyo": "增强式",
    "bosu": "BOSU",
    "med": "药",
    "medicine": "药",
    "stability": "稳定",
    "exercise": "训练",
    "swiss": "瑞士",
    "physio": "物理",
    "wheel": "轮",
    "rollerout": "推出",
    "pullover": "上拉",
    "attachment": "把手",
    "v-bar": "V 杠",
    "vbar": "V 杠",
    "parallel": "双杠",
    "parallette": "双杠架",
    "paralettes": "双杠架",
    "tower": "塔架",
    # 动作词
    "press": "推举",
    "curl": "弯举",
    "row": "划船",
    "raise": "平举",
    "fly": "飞鸟",
    "flies": "飞鸟",
    "flyes": "飞鸟",
    "squat": "深蹲",
    "deadlift": "硬拉",
    "lunge": "弓步",
    "lunges": "弓步蹲",
    "bridge": "桥",
    "thrust": "推",
    "crunch": "卷腹",
    "twist": "扭转",
    "rotation": "旋转",
    "pull": "拉",
    "push": "推",
    "lift": "举",
    "hold": "保持",
    "carry": "行走",
    "walk": "走",
    "swing": "摇摆",
    "throw": "投",
    "flip": "翻转",
    "jerk": "挺",
    "clean": "翻",
    "snatch": "抓",
    "shrug": "耸肩",
    "stretch": "拉伸",
    "mobilization": "活动度",
    "mobilisation": "活动度",
    "rehab": "康复",
    "prehab": "预康复",
    "release": "放松",
    "raise": "平举",
    "pulldown": "下拉",
    "pushdown": "下压",
    "extension": "伸展",
    "flexion": "屈曲",
    "kickback": "后踢",
    "hop": "跳",
    "skip": "跳步",
    "balance": "平衡",
    "burst": "爆发",
    "bounce": "弹",
    "roll": "滚",
    "slide": "滑",
    "skate": "滑",
    "climb": "爬",
    "crawl": "爬",
    "march": "行进",
    "jog": "慢跑",
    "run": "跑",
    "sprint": "冲刺",
    "drag": "拖拽",
    "slam": "砸",
    "chop": "砍",
    "punch": "出拳",
    "kick": "踢",
    "pinch": "夹",
    "crush": "压",
    "grip": "握",
    "floss": "松动",
    "scrape": "刮",
    "snap": "弹",
    "squeeze": "挤压",
    "shuffle": "滑步",
    "step": "步",
    "tap": "轻触",
    "toe": "脚尖",
    "heel": "脚跟",
    "ankle": "踝",
    "wrist": "腕",
    "knee": "膝",
    "elbow": "肘",
    "hip": "髋",
    "waist": "腰",
    "spine": "脊柱",
    "core": "核心",
    "abs": "腹肌",
    "abdominal": "腹肌",
    "obliques": "腹斜",
    "quads": "股四",
    "quad": "股四",
    "quadriceps": "股四头肌",
    "glutes": "臀",
    "glute": "臀",
    "hamstrings": "腘绳",
    "hamstring": "腘绳",
    "calves": "小腿",
    "calf": "小腿",
    "adductor": "内收",
    "abductor": "外展",
    "lats": "背阔",
    "traps": "斜方",
    "delts": "三角肌",
    "delt": "三角肌束",
    "pecs": "胸肌",
    "pec": "胸肌",
    "rhomboids": "菱形肌",
    "rear": "后",
    "front": "前",
    "upper": "上",
    "lower": "下",
    "mid": "中",
    "inner": "内",
    "outer": "外",
    "back": "背",
    "chest": "胸",
    "shoulder": "肩",
    "shoulders": "肩",
    "neck": "颈",
    "arm": "臂",
    "arms": "臂",
    "forearm": "前臂",
    "forearms": "前臂",
    "biceps": "二头",
    "bicep": "二头",
    "triceps": "三头",
    "tricep": "三头",
    "hand": "手",
    "hands": "手",
    "foot": "足",
    "feet": "足",
    "leg": "腿",
    "legs": "腿",
    "thigh": "大腿",
    "thighs": "大腿",
    "lateral": "侧",
    "posterior": "后",
    "anterior": "前",
    "medial": "内侧",
    # 姿态词
    "flat": "平板",
    "incline": "上斜",
    "decline": "下斜",
    "high": "高",
    "low": "低",
    "wide": "宽",
    "narrow": "窄",
    "close": "窄",
    "neutral": "中立",
    "pronated": "正握",
    "supinated": "反握",
    "overhand": "正握",
    "underhand": "反握",
    "reverse": "反",
    "alternate": "交替",
    "alternating": "交替",
    "single": "单",
    "double": "双",
    "one": "单",
    "two": "双",
    "both": "双",
    "each": "每",
    "over": "过",
    "under": "下",
    "side": "侧",
    "deep": "深",
    "shallow": "浅",
    "stiff": "直",
    "straight": "直",
    "bent": "屈",
    "leaning": "前倾",
    "supported": "支撑",
    "unsupported": "无支撑",
    "partial": "半程",
    "full": "全程",
    "slow": "慢速",
    "fast": "快速",
    "speed": "速度",
    "heavy": "大重量",
    "light": "轻重量",
    "dynamic": "动态",
    "static": "静态",
    "explosive": "爆发力",
    "plyometric": "增强式",
    "isometric": "静力",
    "isolation": "孤立",
    "compound": "复合",
    # 方向
    "forward": "前",
    "forwards": "前",
    "frontward": "向前",
    "frontwards": "向前",
    "backward": "后",
    "backwards": "后",
    "upward": "向上",
    "downward": "向下",
    "inward": "向内",
    "outward": "向外",
    "up": "上",
    "down": "下",
    "forwards": "前",
    "backwards": "后",
    "sideways": "横向",
    "clockwise": "顺时针",
    "counterclockwise": "逆时针",
    "horizontal": "水平",
    "vertical": "垂直",
    "diagonal": "对角",
    # 辅助词
    "male": "（男）",
    "female": "（女）",
    "version": "式",
    "variation": "变体",
    "variant": "变体",
    "modified": "改良",
    "advanced": "进阶",
    "beginner": "入门",
    "basic": "基础",
    "standard": "标准",
    "traditional": "传统",
    "modern": "现代",
    "classic": "经典",
    "pro": "专业",
    "max": "最大",
    "rep": "次",
    "reps": "次",
    "cluster": "集群组",
    "drop": "递减",
    "rest": "休息",
    "pause": "停顿",
    "hold": "保持",
    "top": "顶",
    "bottom": "底",
    "range": "幅度",
    "rom": "幅度",
    "part": "部分",
    "internal": "内",
    "external": "外",
    "rotation": "旋转",
    "adduction": "内收",
    "abduction": "外展",
    "flexion": "屈曲",
    "extension": "伸展",
    "cross": "交叉",
    "crossbody": "交叉体",
    "cross-body": "交叉体",
    "cross-over": "交叉",
    "crossover": "交叉",
    "motion": "动态",
    "fixed": "固定",
    "hanging": "悬垂",
    "hang": "悬垂",
    "supported": "支撑",
    "weighted": "负重",
    "loaded": "负重",
    "bodyweight": "自重",
    "free": "自由",
    "assisted": "辅助",
    "unilateral": "单侧",
    "bilateral": "双侧",
    "paused": "停顿",
    "tempo": "节奏",
    "cluster": "集群",
    "half": "半",
    "full": "全",
    "rear": "后",
    "middle": "中",
    "center": "中",
    "concentration": "集中",
    "incline": "上斜",
    "decline": "下斜",
    "flat": "平板",
    "seated": "坐姿",
    "standing": "站姿",
    "lying": "仰卧",
    "prone": "俯卧",
    "supine": "仰卧",
    "kneeling": "跪姿",
    "bent": "俯身",
    "sitting": "坐姿",
    "sitted": "坐姿",
    "quadruped": "四点支撑",
    "all": "全",
    "fours": "四肢",
    "motion": "动态",
    "twisting": "扭转",
    "inverse": "反向",
    "inverted": "反向",
    "reverse": "反向",
    "alternate": "交替",
    "alternating": "交替",
    "between": "间",
    "through": "贯穿",
    "jumping": "跳跃",
    "rocking": "摇摆",
    "rolling": "滚动",
    "ski": "滑雪",
    "skier": "滑雪式",
    "jefferson": "杰斐逊",
    "guillotine": "断头台",
    "bradford": "布拉德福德",
    "rocky": "洛基",
    "meadows": "梅多斯",
    "pendlay": "彭德莱",
    "yates": "耶茨",
    "kroc": "克罗克",
    "spoto": "斯波托",
    "jm": "JM",
    "pallof": "帕洛夫",
    "stairmaster": "登山机",
    "jacob": "雅各",
    "ladder": "梯",
    "backward": "后向",
    "forward": "前向",
    "astride": "分腿",
    "jumps": "跳",
    "balancing": "平衡",
    "board": "板",
    "battling": "搏击",
    "butt": "臀部",
    "butterfly": "蝴蝶",
    "yoga": "瑜伽",
    "pose": "式",
    "bottoms": "举杯",
    "lever": "水平",
    "forth": "来",
    "step": "步",
    "and": "",
    "the": "",
    "a": "",
    "an": "",
    "with": "",
    "using": "",
    "on": "",
    "in": "",
    "at": "",
    "to": "至",
    "of": "",
    "for": "",
    "from": "",
    "into": "",
    "onto": "",
    "towards": "",
    "toward": "",
    "through": "",
    "during": "",
    "per": "每",
    "vs": "对",
    "plus": "加",
    "or": "",
    "off": "",
    "over": "",
    "under": "",
    "out": "",
    "in": "",
    "ii": "二式",
    "iii": "三式",
    "iv": "四式",
    "v": "五式",
    "vi": "六式",
}

# =========================================================================
# 3) MANUAL OVERRIDES for names that just don't make sense via rules
# =========================================================================
MANUAL: dict[str, str] = {
    "all fours squad stretch": "四点支撑蹲式拉伸",
    "alternate heel touchers": "交替触脚跟",
    "alternate lateral pulldown": "交替侧下拉",
    "ankle circles": "踝关节环绕",
    "arm slingers hanging bent knee legs": "吊环悬垂屈膝举腿",
    "arm slingers hanging straight legs": "吊环悬垂直腿举腿",
    "arms apart circular toe touch (male)": "（男）臂分展圆周触脚尖",
    "assisted lying gluteus and piriformis stretch": "辅助仰卧臀肌与梨状肌拉伸",
    "assisted lying leg raise with lateral throw down": "辅助仰卧举腿加侧向甩腿",
    "assisted motion russian twist": "辅助动态俄罗斯转体",
    "assisted parallel close grip pull-up": "辅助双杠窄距引体向上",
    "assisted prone rectus femoris stretch": "辅助俯卧股直肌拉伸",
    "assisted seated pectoralis major stretch with stability ball": "辅助坐姿胸大肌稳定球拉伸",
    "assisted standing triceps extension (with towel)": "辅助站姿毛巾三头伸展",
    "astride jumps (male)": "（男）分腿跳",
    "back and forth step": "前后垫步",
    "back lever": "后水平",
    "backward jump": "后跳",
    "balance board": "平衡板",
    "band assisted wheel rollerout": "弹力带辅助健腹轮推出",
    "band fixed back close grip pulldown": "弹力带背部固定窄距下拉",
    "band fixed back underhand pulldown": "弹力带背部固定反握下拉",
    "band horizontal pallof press": "弹力带水平帕洛夫推",
    "band jack knife sit-up": "弹力带折刀仰卧起坐",
    "band kneeling twisting crunch": "弹力带跪姿扭转卷腹",
    "band lying hip internal rotation": "弹力带仰卧髋内旋",
    "band one arm twisting chest press": "弹力带单臂扭转推胸",
    "band one arm twisting seated row": "弹力带单臂扭转坐姿划船",
    "band seated hip internal rotation": "弹力带坐姿髋内旋",
    "band standing twisting crunch": "弹力带站姿扭转卷腹",
    "band twisting overhead press": "弹力带扭转过头推举",
    "band two legs calf raise - (band under both legs) v. 2": "弹力带双腿提踵二式（双腿踩）",
    "band vertical pallof press": "弹力带垂直帕洛夫推",
    "barbell glute bridge two legs on bench (male)": "（男）杠铃双腿凳上臀桥",
    "barbell guillotine bench press": "杠铃断头台卧推",
    "barbell jefferson squat": "杠铃杰斐逊深蹲",
    "barbell lying lifting (on hip)": "杠铃仰卧髋上举",
    "barbell one leg squat": "杠铃单腿深蹲",
    "barbell palms down wrist curl over a bench": "杠铃凳上掌心向下腕弯举",
    "barbell palms up wrist curl over a bench": "杠铃凳上掌心向上腕弯举",
    "barbell revers wrist curl v. 2": "杠铃反腕弯举二式",
    "barbell seated behind head military press": "杠铃坐姿颈后军式推举",
    "barbell seated bradford rocky press": "杠铃坐姿布拉德福洛基推举",
    "barbell seated close grip behind neck triceps extension": "杠铃坐姿窄距颈后三头伸展",
    "barbell sitted alternate leg raise": "杠铃坐姿交替举腿",
    "barbell sitted alternate leg raise (female)": "（女）杠铃坐姿交替举腿",
    "barbell skier": "杠铃滑雪式摇摆",
    "barbell speed squat": "杠铃速度深蹲",
    "barbell squat (on knees)": "杠铃跪姿深蹲",
    "barbell squat jump step rear lunge": "杠铃深蹲跳接后撤弓步",
    "barbell standing rocking leg calf raise": "杠铃站姿摇摆提踵",
    "basic toe touch (male)": "（男）基础触脚尖",
    "battling ropes": "战绳",
    "behind head chest stretch": "头后胸部拉伸",
    "bench dip (knees bent)": "屈膝凳上臂屈伸",
    "bottoms-up": "举杯式",
    "box jump down with one leg stabilization": "跳箱下单腿稳定",
    "butt-ups": "臀部上抬",
    "butterfly yoga pose": "蝴蝶式",
    "cable assisted inverse leg curl": "绳索辅助反向腿弯举",
    "cable bar lateral pulldown": "绳索杠侧下拉",
    "cable concentration extension (on knee)": "绳索膝上集中伸展",
    "cable cross-over lateral pulldown": "绳索交叉侧下拉",
    "cable cross-over revers fly": "绳索交叉反向飞鸟",
    "cable forward raise": "绳索前平举",
    "cable hip adduction": "绳索髋内收",
    "cable judo flip": "绳索柔道翻转",
    "cable kneeling rear delt row (with rope) (male)": "（男）绳索跪姿绳索后束划船",
    "cable lateral pulldown (with rope attachment)": "绳索把手侧下拉",
    "cable lateral pulldown with v-bar": "V 杠绳索侧下拉",
    "cable lying extension pullover (with rope attachment)": "绳索把手仰卧伸展上拉",
    "cable middle fly": "绳索中胸飞鸟",
    "cable one arm lateral bent-over": "绳索单臂俯身侧平举",
    "cable overhead triceps extension (rope attachment)": "绳索把手过头三头伸展",
    "bodyweight squatting row (with towel)": "自重毛巾蹲式划船",
    "bodyweight standing one arm row (with towel)": "自重站姿单臂毛巾划船",
    "bodyweight standing row (with towel)": "自重站姿毛巾划船",
}


# =========================================================================
# TRANSLATION PIPELINE
# =========================================================================

def normalize(name: str) -> str:
    s = name.lower().strip()
    s = re.sub(r"[()\[\]{}]", " ", s)
    s = re.sub(r"[/,\\]", " ", s)
    s = s.replace("–", " ").replace("—", " ").replace("-", " - ")
    s = re.sub(r"\s+", " ", s).strip()
    return s


def translate(name: str) -> str:
    if name in MANUAL:
        return MANUAL[name]

    s = normalize(name)

    # ---- Phase A: compound regex replacements ---------------------------
    for eng, zh in COMPOUNDS:
        pat = re.compile(r"(?<!\w)" + re.escape(eng) + r"(?!\w)", re.IGNORECASE)
        s, n = pat.subn(" " + zh + " ", s)
        if n and len(s) < 2:  # keep going
            pass

    s = re.sub(r"\s+", " ", s).strip()

    # ---- Phase B: word-by-word ----------------------------------------
    tokens = re.split(r"\s+|(?<=[A-Za-z\u4e00-\u9fff])(?=-)|(?<=-)(?=[A-Za-z\u4e00-\u9fff])", s)
    out: list[str] = []
    for tok in tokens:
        tok = tok.strip(" -_.")
        if not tok:
            continue
        # pure Chinese / digit -> keep
        if re.fullmatch(r"[\u4e00-\u9fff0-9×（）]+", tok):
            out.append(tok)
            continue
        if tok.isdigit():
            out.append(tok)
            continue
        if tok in WORDS:
            w = WORDS[tok]
            if w:
                out.append(w)
            continue
        low = tok.lower()
        if low in WORDS:
            w = WORDS[low]
            if w:
                out.append(w)
            continue
        # try singular/plural variants
        if len(low) > 2 and low.endswith("s") and low[:-1] in WORDS:
            w = WORDS[low[:-1]]
            if w:
                out.append(w)
            continue
        if len(low) > 3 and low.endswith("es") and low[:-2] in WORDS:
            w = WORDS[low[:-2]]
            if w:
                out.append(w)
            continue
        if len(low) > 3 and low.endswith("ed") and low[:-2] in WORDS:
            w = WORDS[low[:-2]]
            if w:
                out.append(w)
            continue
        if len(low) > 3 and low.endswith("ing") and low[:-3] in WORDS:
            w = WORDS[low[:-3]]
            if w:
                out.append(w)
            continue
        if len(low) > 4 and low.endswith("ly") and low[:-2] in WORDS:
            w = WORDS[low[:-2]]
            if w:
                out.append(w)
            continue
        # Try subword lookup: split into smaller bits on dash again
        if "-" in tok:
            bits = tok.split("-")
            ok_all = all(b.lower() in WORDS for b in bits if b)
            if ok_all:
                for b in bits:
                    bw = WORDS.get(b.lower(), "")
                    if bw:
                        out.append(bw)
                continue
        # Keep single Latin tokens 3+ chars (name or brand or we missed it)
        # drop very short / noise
        if len(tok) <= 2:
            continue
        # Keep numbers + digits mixes
        if re.fullmatch(r"[a-z0-9.]+", tok) and (any(c.isdigit() for c in tok) or len(tok) <= 4):
            out.append(tok)
            continue
        # Unknown latin -> append capitalized version as last-resort hint
        out.append(tok.title())

    zh = "".join(out).strip()
    zh = re.sub(r"\s+", "", zh)

    # ---- Pretty-fix common bad reorders -------------------------------
    zh = (
        zh.replace("哑铃哑铃", "哑铃")
        .replace("杠铃杠铃", "杠铃")
        .replace("绳索绳索", "绳索")
        .replace("壶铃壶铃", "壶铃")
        .replace("史密斯机史密斯机", "史密斯机")
        .replace("弹力带弹力带", "弹力带")
        .replace("单腿单腿", "单腿")
        .replace("单臂单臂", "单臂")
        .replace("双腿双腿", "双腿")
        .replace("双臂双臂", "双臂")
        .replace("二头二头", "二头")
        .replace("三头三头", "三头")
        .replace("（男）（男）", "（男）")
        .replace("（女）（女）", "（女）")
    )

    # If string ends with equipment name + was preceded by action, Chinese prefers 器械+动作
    # E.g. "交替二头弯举哑铃" -> "哑铃交替二头弯举"
    GEAR_SUFFIXES = (
        "哑铃", "杠铃", "绳索", "壶铃", "EZ曲杆", "EZ 曲杆", "史密斯机",
        "地雷管", "六角杠", "弹力带", "T 杠", "T杠", "奥杆", "壶铃",
    )
    for g in GEAR_SUFFIXES:
        if zh.endswith(g) and len(zh) > len(g) + 2:
            zh = g + zh[: -len(g)]
            break

    if not zh:
        zh = name.title()
    return zh


def main() -> None:
    data = json.loads(SRC.read_text(encoding="utf-8"))
    bad: list[str] = []
    for ex in data:
        name = ex.get("name", "")
        zh = translate(name)
        ex["name_zh"] = zh
        latin_count = len(re.findall(r"[A-Za-z]", zh))
        if latin_count > 4:
            bad.append(f"{name:60s} -> {zh}")

    SRC.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    report = Path(__file__).parent / "translation_report.txt"
    report.write_text("\n".join(bad[:1000]), encoding="utf-8")
    print(f"Done: {len(data)} exercises, remaining Latin-heavy: {len(bad)}")
    for line in bad[:50]:
        print("   ", line)


if __name__ == "__main__":
    main()
